# Site settings
title: CestPasDur.com
email: damien.gouyette@gmail.com
description: ""

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000/" # the base hostname & protocol for your site
twitter_username: cestpasdur
github_username:  dgouyette

comments: true

# Build settings
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data", "tables"]
